[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_port = COM3
monitor_port = COM3
monitor_speed = 115200
upload_speed = 115200

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit Unified Sensor

[env:esp32dev_motion_sim]
extends = env:esp32dev
build_flags = -DCROSSWIND_MOTION_SIMULATION=1

[env:esp32dev_battery_sim]
extends = env:esp32dev
build_flags =
    -DCROSSWIND_MOTION_SIMULATION=1
    -DCROSSWIND_BATTERY_SIMULATION=1
