[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_port = COM3
monitor_port = COM3
monitor_speed = 115200
upload_speed = 115200

lib_deps =
    olikraus/U8g2 @ ^2.36.18
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit Unified Sensor
